--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: online_poll_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE online_poll_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


ALTER DATABASE online_poll_db OWNER TO postgres;

\connect online_poll_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Answers" (
    "Id" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    "Text" text NOT NULL
);


ALTER TABLE public."Answers" OWNER TO postgres;

--
-- Name: Answers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Answers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Answers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Interviews; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Interviews" (
    "Id" integer NOT NULL,
    "SurveyId" integer NOT NULL,
    "IntervieweeName" text NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Interviews" OWNER TO postgres;

--
-- Name: Interviews_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Interviews" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Interviews_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Questions" (
    "Id" integer NOT NULL,
    "SurveyId" integer NOT NULL,
    "Text" text NOT NULL
);


ALTER TABLE public."Questions" OWNER TO postgres;

--
-- Name: Questions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Questions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Questions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Results; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Results" (
    "Id" integer NOT NULL,
    "AnswerId" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    "InterviewId" integer NOT NULL
);


ALTER TABLE public."Results" OWNER TO postgres;

--
-- Name: Results_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Results" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Results_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Surveys; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Surveys" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL
);


ALTER TABLE public."Surveys" OWNER TO postgres;

--
-- Name: Surveys_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Surveys" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Surveys_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Data for Name: Answers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Answers" VALUES (1, 1, 'Суп');
INSERT INTO public."Answers" VALUES (2, 1, 'Каша');
INSERT INTO public."Answers" VALUES (3, 1, 'Торт');
INSERT INTO public."Answers" VALUES (4, 2, 'Собака');
INSERT INTO public."Answers" VALUES (5, 2, 'Кошка');
INSERT INTO public."Answers" VALUES (6, 2, 'Рыбка');
INSERT INTO public."Answers" VALUES (7, 3, 'Футбол');
INSERT INTO public."Answers" VALUES (8, 3, 'Гимнастика');
INSERT INTO public."Answers" VALUES (9, 3, 'Легкая Атлетика');


--
-- Data for Name: Interviews; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Interviews" VALUES (1, 1, 'Иванов Иван Сергеевич', '2025-07-05 22:29:20.099+03', '2025-07-05 17:29:28.113+03');


--
-- Data for Name: Questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Questions" VALUES (1, 1, 'Какая ваша любимая еда?');
INSERT INTO public."Questions" VALUES (2, 1, 'Какие животные вам нравятся?');
INSERT INTO public."Questions" VALUES (3, 1, 'Какие виды спорта предпочитаете?');


--
-- Data for Name: Results; Type: TABLE DATA; Schema: public; Owner: postgres
--



--
-- Data for Name: Surveys; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."Surveys" VALUES (1, 'Что вы любите', 'Милая анкета');


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20250705162230_InitialCreate', '9.0.6');
INSERT INTO public."__EFMigrationsHistory" VALUES ('20250705183210_ChangeDeleteStrategyAndAddInterviews', '9.0.6');


--
-- Name: Answers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Answers_Id_seq"', 9, true);


--
-- Name: Interviews_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Interviews_Id_seq"', 1, true);


--
-- Name: Questions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Questions_Id_seq"', 3, true);


--
-- Name: Results_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Results_Id_seq"', 10, true);


--
-- Name: Surveys_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Surveys_Id_seq"', 1, true);


--
-- Name: Answers PK_Answers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "PK_Answers" PRIMARY KEY ("Id");


--
-- Name: Interviews PK_Interviews; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Interviews"
    ADD CONSTRAINT "PK_Interviews" PRIMARY KEY ("Id");


--
-- Name: Questions PK_Questions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "PK_Questions" PRIMARY KEY ("Id");


--
-- Name: Results PK_Results; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Results"
    ADD CONSTRAINT "PK_Results" PRIMARY KEY ("Id");


--
-- Name: Surveys PK_Surveys; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Surveys"
    ADD CONSTRAINT "PK_Surveys" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Answers_QuestionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Answers_QuestionId" ON public."Answers" USING btree ("QuestionId");


--
-- Name: IX_Interviews_SurveyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Interviews_SurveyId" ON public."Interviews" USING btree ("SurveyId");


--
-- Name: IX_Questions_SurveyId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Questions_SurveyId" ON public."Questions" USING btree ("SurveyId");


--
-- Name: IX_Results_AnswerId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Results_AnswerId" ON public."Results" USING btree ("AnswerId");


--
-- Name: IX_Results_InterviewId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Results_InterviewId" ON public."Results" USING btree ("InterviewId");


--
-- Name: IX_Results_QuestionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Results_QuestionId" ON public."Results" USING btree ("QuestionId");


--
-- Name: idx_finished_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_finished_at ON public."Interviews" USING btree ("FinishedAt");


--
-- Name: idx_interviewee_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_interviewee_name ON public."Interviews" USING btree ("IntervieweeName");


--
-- Name: idx_started_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_started_at ON public."Interviews" USING btree ("StartedAt");


--
-- Name: Answers FK_Answers_Questions_QuestionId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "FK_Answers_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES public."Questions"("Id") ON DELETE RESTRICT;


--
-- Name: Interviews FK_Interviews_Surveys_SurveyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Interviews"
    ADD CONSTRAINT "FK_Interviews_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES public."Surveys"("Id") ON DELETE RESTRICT;


--
-- Name: Questions FK_Questions_Surveys_SurveyId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "FK_Questions_Surveys_SurveyId" FOREIGN KEY ("SurveyId") REFERENCES public."Surveys"("Id") ON DELETE RESTRICT;


--
-- Name: Results FK_Results_Answers_AnswerId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Results"
    ADD CONSTRAINT "FK_Results_Answers_AnswerId" FOREIGN KEY ("AnswerId") REFERENCES public."Answers"("Id") ON DELETE RESTRICT;


--
-- Name: Results FK_Results_Interviews_InterviewId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Results"
    ADD CONSTRAINT "FK_Results_Interviews_InterviewId" FOREIGN KEY ("InterviewId") REFERENCES public."Interviews"("Id") ON DELETE RESTRICT;


--
-- Name: Results FK_Results_Questions_QuestionId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Results"
    ADD CONSTRAINT "FK_Results_Questions_QuestionId" FOREIGN KEY ("QuestionId") REFERENCES public."Questions"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

